version: '3.9'

services:
  web:
    image: limited-public-profile-web:15.2
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
      - vendor-store:/var/www/html/vendor
      - node_modules-store:/var/www/html/node_modules

  php:
    image: limited-public-profile-php:8.3
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    volumes:
      - ./src:/var/www/html
      - vendor-store:/var/www/html/vendor
      - node_modules-store:/var/www/html/node_modules
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  db:
    image: limited-public-profile-db:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  vendor-store:
  node_modules-store:
